Revert "lib/, src/ tests/: Unname unused parameters in callbacks"
This reverts commit 9e711e2240c72017dacf088d2931fb26dc6e8fed.

We cannot just uname these unused parameters because gcc 10
need them. There will be error like below with gcc 10:

  lib/copydir.c:103:11: error: parameter name omitted

Fixes: https://github.com/shadow-maint/shadow/issues/1530

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>